name: Burp CI-driven scan test

on:
  workflow_dispatch:     # allows manual runs
  push:                  # optional – runs on pushes to the repo
    branches: [ main ]

jobs:
  burp-scan:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # opt in to Node 24 now

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI-driven scan Action Step
        uses: PortSwigger/ci-driven-scan-github-action@main
        with:
          enterprise-server-url: https://2226816d.portswigger.cloud
          enterprise-api-key: jqc5HLCO9nNAPjnlnXl92zuwkOepL0jC
          start-url: "https://vulnerable-website.com/"
